In [2]:
import cv2
import numpy as np

In [2]:
print(cv2.__version__)

4.6.0


In [2]:
# img = cv2.imread('1187753.png') #D:/jinli/Documents/Exam_ExerciseACSAI/AI_lab/1187753.png
#img = cv2.imread('1188019.jpg') 
img = cv2.imread('gerry.png') 
#print(img)
# it is stored as numpy array, so we can use numpy functions to manipulate it
print(f'Width: {img.shape[1]} pixels')
print(f'Height: {img.shape[0]} pixels')
print(f'Channels: {img.shape[2]}') #3 dimension: RGB image, 256rowsx256colsx3channels

Width: 768 pixels
Height: 1024 pixels
Channels: 3


In [5]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
img = cv2.imread('gerry.png') #second argument is a type of img you want to load
#1 -> pass the img as RGB
#0 -> read the img as grey-scale img -> there is only one channel of colors so there is no shape[2]
#There is another, 4th channel, it is transparency
print(f'columns: {img.shape[1]}')
print(f'rows: {img.shape[0]} ')
print(f'Shape: {img.shape}') #3 dimension: RGB image, 256rowsx256colsx3channels
# cv2.imshow('Image', img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

columns: 768
rows: 1024 
Shape: (1024, 768, 3)


In [7]:
def save(x):
    cv2.imwrite('test.png', x) 

In [42]:
#How to access single portion of the img
img[0,0] = 0
corner = img[0:200, 0:200]
img[0:50, 0:50] = (200, 100, 255)
save(img[0:50, 0:50])

#Insight if the img is gray scale it will accept only one arg because it has only one channel'
# if the img is rgb then it accepts 3



In [43]:
#How to draaw on the img
# imgs in opencv -> numpy arrays
img = np.zeros((500, 500, 3), dtype = 'uint8')

#define a color
green = (0, 255, 0)
#drawing a line
cv2.line(img, (10,10), (200,200), green, 3) #1st param: img , 2 strting pt, 3rd ending pt
#drawing a rectangle
red = (0, 0, 255)
cv2.rectangle(img, (30,30), (70,70), red, -3)
#drawing a circle
white = (255, 255, 255)
(centerx, centery) = (img.shape[0]//2, img.shape[1]//2)
cv2.circle(img, (centerx, centery), 20, white, -1)
save(img)



In [56]:
#Image processing
(b,g,r) = cv2.split(img) #splits the channels 
img_copy = cv2.merge((b,g,r))
b = img[:, :, 2]
save(b)



In [57]:
#Transorming the images with open cv
#multiplying be matricies also provided by opencv
upscaling_img = cv2.resize(img, (img.shape[0]*2, img.shape[1]*2))
save(upscaling_img)

In [83]:
img = cv2.imread('gerry.png')
upscale_img = cv2.resize(img, None, fx=3, fy =0.5)
save(upscale_img)

#with matrix 2x3 u can apply more transformations to your img
rows, cols = img.shape[1], img.shape[0]
M = np.float32([[1,0, 50] , [0,1, 100]])# an array with a type float, mtrx [1,0,0],[0,1,0] means no transformation applied
# now it means move 50 px to the right and 100 pixels to the bootom. Negative tx to the right, negative ty to the up
# Affine transformation
dst_img = cv2.warpAffine(img, M, (rows*2, cols*2))

#Rotation 
M = cv2.getRotationMatrix2D((cols//2, rows//2), 180, 1)
dst_img = cv2.warpAffine(img, M, (rows*2, cols*2))
save(dst_img)

#if u ve 2 sets of points we can find the transformation that allows us to go from first set to the second (done with panorama program)
# extract som pts from 1 st img, and the same pts from the second, then we can find the transformation between the pts  to stitch them together
pts_1 = np.float32([[135,45], [385,45],[135,230]])
pts_2 = np.float32([[135,45], [385,45],[150,230]])
M = cv2.getAffineTransform(pts_1, pts_2)
# returns a matrix such that if you apply M pts_1 = pts_2
dst_img = cv2.warpAffine(pts_1,M, (800, 800))
print(M)


[[ 1.00000000e+00  8.10810811e-02 -3.64864865e+00]
 [ 3.28109106e-18  1.00000000e+00 -1.26322006e-15]]


In [84]:
#next intro part2
print(cv2.__version__)

4.6.0


In [85]:
print(np.__version__)

1.26.4


In [86]:
pts_1 = np.float32([[135, 45], [385, 45], [135, 230]])
pts_2 = np.float32([[135, 45], [385, 45], [150, 230]])
M = cv2.getAffineTransform(pts_1, pts_2)
dst_img = cv2.warpAffine(pts_1,M, (800, 800))
print(M)

[[ 1.00000000e+00  8.10810811e-02 -3.64864865e+00]
 [ 3.28109106e-18  1.00000000e+00 -1.26322006e-15]]


In [91]:
#exerciise with gerry
img = cv2.imread('gerry.png')
ims = cv2.resize(img, None, fx = 0.5, fy = 0.5)
save(ims)


In [92]:
# to get only gerry's picture we will nedd 4 corners of the actual picture
#we will get transformation matrix and apply it to get the gerry
#1 Getting the corners 
#Corner coordinates
src_points = np.array(
    [
        [28, 227],
        [131,987],
        [730, 860],
        [572, 149]
    ], np.float32  #opencv expect this type of float for transformation matrix
)
dst_points = np.array(
    [
        [0,0],
        [0, 800],
        [600, 800],
        [600, 0]
    ], np.float32
)
M = cv2.getPerspectiveTransform(src_points, dst_points) 
out_image = cv2.warpPerspective(img, M, (600,800))
save(out_image)

In [ ]:
img = cv2.imread('gerry.png')
#create a cpopy of tkhe input img
img_copy = img.copy()
img_copy = cv2.resize(img_copy, None, fx = 0.5, fy = 0.5)

#defining starting pts
src_points = []
#defining destionation points
dst_points = np.array(
    [
        [0,0],
        [0, 800],
        [600, 800],
        [600, 0]
    ], np.float32
)
def onClick(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        if len(src_points) < 4:
            src_points.append([x,y])
            cv2.circle(img_copy(x,y), 10, (0,0,255), -1)
            cv2.imshow('Img', img_copy)
    cv2.setMouseCallback('Img', onClick)
cv2.imshow('Img', img_copy) #use img_copy otherwise the callback will be applied on the original
cv2.waitKey(0)
cv2.destroyAllWindows()
